import { AppPage } from "./common-interface";
import { 
    homeOutline, homeSharp,
    peopleOutline, peopleSharp,
    personOutline, personSharp,
    calendarOutline, calendarSharp,
    documentTextOutline, documentTextSharp,
    schoolOutline, schoolSharp,
    walletOutline, walletSharp,
    bookmarksOutline, bookmarksSharp,
    timeOutline, timeSharp,
    ribbonOutline, ribbonSharp,
    imagesOutline, imagesSharp,
    informationCircleOutline, informationCircleSharp,
    callOutline, callSharp,
    bookOutline, bookSharp,
    trophyOutline, trophySharp,
    newspaperOutline, newspaperSharp,
    chatbubbleOutline, chatbubbleSharp,
    mapOutline, mapSharp,
    personAddOutline, personAddSharp,
    businessOutline, businessSharp,
    listOutline, listSharp,
    journalOutline, journalSharp
  } from 'ionicons/icons';
  
export const RoutesListDynamic : AppPage[] = [
    {
      title: 'Dashboard',
      url: '/dashboard',
      iosIcon: homeOutline,
      mdIcon: homeSharp,
    },
    {
      title: 'Students List',
      url: '/students-list',
      iosIcon: peopleOutline,
      mdIcon: peopleSharp,
    },
    {
      title: 'Staff List',
      url: '/staff-list',
      iosIcon: peopleOutline,
      mdIcon: peopleSharp,
    },
    {
      title: 'Profile',
      url: '/profile',
      iosIcon: personOutline,
      mdIcon: personSharp,
    },
    {
      title: 'My Attendance',
      url: '/my-attendance',
      iosIcon: calendarOutline,
      mdIcon: calendarSharp,
    },
    {
      title: 'My Progress Card',
      url: '/my-progress-card',
      iosIcon: documentTextOutline,
      mdIcon: documentTextSharp,
    },
    {
      title: 'Academic Subjects',
      url: '/academic-subjects',
      iosIcon: schoolOutline,
      mdIcon: schoolSharp,
    },
    {
      title: 'Fee Structure / My Dues',
      url: '/fee-structure',
      iosIcon: walletOutline,
      mdIcon: walletSharp,
    },
    {
      title: 'Time Table',
      url: '/time-table',
      iosIcon: timeOutline,
      mdIcon: timeSharp,
    },
    {
      title: 'Extra Curricular Activities / Competitions',
      url: '/extra-curricular-activities',
      iosIcon: ribbonOutline,
      mdIcon: ribbonSharp,
    },
    {
      title: 'Gallery',
      url: '/gallery',
      iosIcon: imagesOutline,
      mdIcon: imagesSharp,
    },
    {
      title: 'About',
      url: '/about',
      iosIcon: informationCircleOutline,
      mdIcon: informationCircleSharp,
    },
    {
      title: 'Contact Us',
      url: '/contact-us',
      iosIcon: callOutline,
      mdIcon: callSharp,
    },
    {
      title: 'Courses',
      url: '/courses',
      iosIcon: bookOutline,
      mdIcon: bookSharp,
    },
    {
      title: 'Achievements',
      url: '/achievements',
      iosIcon: trophyOutline,
      mdIcon: trophySharp,
    },
    {
      title: 'School Wibe Posts',
      url: '/school-wibe',
      iosIcon: newspaperOutline,
      mdIcon: newspaperSharp,
    },
    {
      title: 'Messages',
      url: '/messages',
      iosIcon: chatbubbleOutline,
      mdIcon: chatbubbleSharp,
    },
    {
      title: 'Exam Schedules',
      url: '/exam-schedules',
      iosIcon: calendarOutline,
      mdIcon: calendarSharp,
    },
    {
      title: 'Assets',
      url: '/assets',
      iosIcon: businessOutline,
      mdIcon: businessSharp,
    },
    {
      title: 'Remainders',
      url: '/remainders',
      iosIcon: listOutline,
      mdIcon: listSharp,
    },
    {
      title: 'Diary',
      url: '/diary',
      iosIcon: journalOutline,
      mdIcon: journalSharp,
    },
  ];