import { AppPage } from "./common-interface";
import {
  homeOutline, homeSharp,
  peopleOutline, peopleSharp,
  calendarOutline, calendarSharp,
  documentTextOutline, documentTextSharp,
  schoolOutline, schoolSharp,
  walletOutline, walletSharp,
  ribbonOutline, ribbonSharp,
  imagesOutline, imagesSharp,
  informationCircleOutline, informationCircleSharp,
  callOutline, callSharp,
  bookOutline, bookSharp,
  trophyOutline, trophySharp,
  newspaperOutline, newspaperSharp,
  chatbubbleOutline, chatbubbleSharp,
  businessOutline, businessSharp,
  listOutline, listSharp,
  journalOutline, journalSharp,
  documentAttachOutline,
  documentAttachSharp,
  imageOutline,
  cubeOutline,
  gridOutline,
  chatboxOutline,
  documentOutline,
  timeOutline,
  peopleCircleOutline,
  sparklesOutline,
  gameControllerOutline,
  calendarNumberOutline,
  idCardOutline
} from 'ionicons/icons';

export const RoutesListDynamic: AppPage[] = [
  {
    title: 'Dashboard',
    url: '/dashboard',
    iosIcon: homeOutline,
    mdIcon: homeSharp,
  },
  {
    title: 'Attendance',
    url: '/attendance',
    iosIcon: calendarOutline,
    mdIcon: calendarSharp,
  },
  {
    title: 'Progress Card',
    url: '/progress-card',
    iosIcon: documentTextOutline,
    mdIcon: documentTextSharp,
  },
  {
    title: 'Subjects',
    url: '/subjects',
    iosIcon: schoolOutline,
    mdIcon: schoolSharp,
  },
  {
    title: 'Messages',
    url: '/messages',
    iosIcon: chatbubbleOutline,
    mdIcon: chatbubbleSharp,
  },
  {
    title: 'Documents',
    url: '/documents',
    iosIcon: documentAttachOutline,
    mdIcon: documentAttachSharp,
  },
  {
    title: 'Students List',
    url: '/students-list',
    iosIcon: peopleOutline,
    mdIcon: peopleSharp,
  },
  {
    title: 'Staff List',
    url: '/staff-list',
    iosIcon: peopleOutline,
    mdIcon: peopleSharp,
  },
  {
    title: 'Fee Structure / My Dues',
    url: '/fee-structure',
    iosIcon: walletOutline,
    mdIcon: walletSharp,
  },
  {
    title: 'Calendar',
    url: '/calendar',
    iosIcon: calendarOutline,
    mdIcon: calendarSharp,
  },
  {
    title: 'Ex-Circular',
    url: '/ex-circular',
    iosIcon: ribbonOutline,
    mdIcon: ribbonSharp,
  },
  {
    title: 'Gallery',
    url: '/gallery',
    iosIcon: imagesOutline,
    mdIcon: imagesSharp,
  },
  {
    title: 'About',
    url: '/about',
    iosIcon: informationCircleOutline,
    mdIcon: informationCircleSharp,
  },
  {
    title: 'Contact Us',
    url: '/contact-us',
    iosIcon: callOutline,
    mdIcon: callSharp,
  },
  {
    title: 'Courses',
    url: '/courses',
    iosIcon: bookOutline,
    mdIcon: bookSharp,
  },
  {
    title: 'Achievements',
    url: '/achievements',
    iosIcon: trophyOutline,
    mdIcon: trophySharp,
  },
  {
    title: 'Vibe',
    url: '/school-vibe',
    iosIcon: newspaperOutline,
    mdIcon: newspaperSharp,
  },
  {
    title: 'Exam Schedules',
    url: '/exam-schedules',
    iosIcon: calendarOutline,
    mdIcon: calendarSharp,
  },
  {
    title: 'Assets',
    url: '/assets',
    iosIcon: businessOutline,
    mdIcon: businessSharp,
  },
  {
    title: 'Home Work',
    url: '/home-work',
    iosIcon: listOutline,
    mdIcon: listSharp,
  },
  {
    title: 'Diary',
    url: '/diary',
    iosIcon: journalOutline,
    mdIcon: journalSharp,
  },
];

export const chipsDataPublic = [
  { id: 16, moduleName: 'Ex-Circular', icon: gameControllerOutline, redirectTo: '/ex-circular' },
  { id: 17, moduleName: 'Gallery', icon: imageOutline, redirectTo: '/gallery' },
  { id: 18, moduleName: 'Achievements', icon: trophyOutline, redirectTo: '/achievements' },
  { id: 19, moduleName: 'Contact-Us', icon: callOutline, redirectTo: '/contact-us' },
  { id: 20, moduleName: 'About', icon: informationCircleOutline, redirectTo: '/about' },
  { id: 21, moduleName: 'Courses', icon: bookOutline, redirectTo: '/courses' }
];
export const chipsDataPrivate = [
  { id: 1, moduleName: 'Staff', icon: peopleCircleOutline, redirectTo: '/staff-list' },
  { id: 2, moduleName: 'Students', icon: peopleOutline, redirectTo: '/students-list' },
  { id: 3, moduleName: 'Progress Card', icon: documentTextOutline, redirectTo: '/progress-card-unit-add' },
  { id: 4, moduleName: 'Class - Sections', icon: gridOutline, redirectTo: '/school-classes' },
  { id: 5, moduleName: 'Time Table', icon: timeOutline, redirectTo: '/time-table' },
  { id: 6, moduleName: 'Attendance', icon: idCardOutline, redirectTo: '/attendance-by-class' },
  { id: 7, moduleName: 'Home Works', icon: bookOutline, redirectTo: '/home-work' },
  { id: 8, moduleName: 'Class Subjects', icon: cubeOutline, redirectTo: '/subjects' },
  { id: 9, moduleName: 'Messages', icon: chatboxOutline, redirectTo: '/messages' },
  { id: 10, moduleName: 'Documents', icon: documentOutline, redirectTo: '/documents' },
  { id: 11, moduleName: 'Calendar', icon: calendarOutline, redirectTo: '/calendar' },
  { id: 12, moduleName: 'Assets', icon: businessOutline, redirectTo: '/assets' },
  { id: 13, moduleName: 'Vibe', icon: sparklesOutline, redirectTo: '/school-vibe' },
  { id: 14, moduleName: 'Exam Schedules', icon: calendarNumberOutline, redirectTo: '/exam-schedules' },
  { id: 15, moduleName: 'Fees Dues', icon: walletOutline, redirectTo: '/fee-structure' },
];


export const studentsChipsData = [
  { id: 1, moduleName: 'Attendance', icon: idCardOutline, redirectTo: '/attendance' },
  { id: 2, moduleName: 'Progress Card', icon: documentTextOutline, redirectTo: '/progress-card' },
  { id: 3, moduleName: 'Home Work', icon: bookOutline, redirectTo: '/home-work' },
  { id: 4, moduleName: 'My Subjects', icon: cubeOutline, redirectTo: '/subjects' },
  { id: 5, moduleName: 'Messages', icon: chatboxOutline, redirectTo: '/messages' },
  { id: 6, moduleName: 'Documents', icon: documentOutline, redirectTo: '/documents' },
  { id: 7, moduleName: 'My Staff', icon: peopleCircleOutline, redirectTo: '/staff-list' },
  { id: 8, moduleName: 'My Friends', icon: peopleOutline, redirectTo: '/students-list' },
  { id: 9, moduleName: 'Calendar', icon: calendarOutline, redirectTo: '/calendar' },
  { id: 10, moduleName: 'Vibe', icon: sparklesOutline, redirectTo: '/school-vibe' },
  { id: 11, moduleName: 'Exam Schedules', icon: calendarNumberOutline, redirectTo: '/exam-schedules' },
  { id: 12, moduleName: 'My Dues', icon: walletOutline, redirectTo: '/fee-structure' },
  { id: 13, moduleName: 'Assets', icon: businessOutline, redirectTo: '/assets' },
  { id: 14, moduleName: 'Ex-Circular', icon: gameControllerOutline, redirectTo: '/ex-circular' },
  { id: 15, moduleName: 'Gallery', icon: imageOutline, redirectTo: '/gallery' },
  { id: 16, moduleName: 'Achievements', icon: trophyOutline, redirectTo: '/achievements' },
  { id: 17, moduleName: 'Contact-Us', icon: callOutline, redirectTo: '/contact-us' },
  { id: 18, moduleName: 'About', icon: informationCircleOutline, redirectTo: '/about' },
];